# Sample .travis.yml for R projects

language: r
r:
#  - oldrel
  - release
#  - devel
warnings_are_errors: true
sudo: false
cache: packages
latex: false

env:
 global:
   - CRAN: http://cran.rstudio.com

notifications:
  email:
    on_success: change
    on_failure: change

# System dependencies for HTTP calling
#r_binary_packages:
# - dplyr

#r_packages:
#  - devtools
#  - Rcpp

before_deploy:
  - R CMD INSTALL .
  - Rscript -e 'pkgdown::build_site()'
#  - npm install netlify-cli -g

r_github_packages:
 - hadley/pkgdown

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_PAT
  keep-history: true
#  repo: ismayc/inferdown
#  target_branch: master

after_success:
  - Rscript -e 'covr::codecov()'
#  - bash ./.deploy_pkgdown.sh

